export const CarMakes = [
  {label: "Ford",name: "Ford"},{label: "Honda",name: "Honda"},
  {label: "Hyundai",name: "Hyundai"},
  {label: "Mazda",name: "Mazda"},
  {label: "Toyota",name: "Toyota"},
  {label: "Mercedes",name: "Mercedes"},
  {label: "Audi",name: "Audi"},
  {label: "BMW",name: "BMW"},
  {label: "Lexus",name: "Lexus"},
  {label: "Chevrolet",name: "Chevrolet"},
  {label: "Ferrari",name: "Ferrari"},
  {label: "Jaguar",name: "Jaguar"},
  {label: "Lamborghini",name: "Lamborghini"},
  {label: "Land Rover",name: "Land Rover"},
  {label: "Nissan",name: "Nissan"},
  {label: "Porsche",name: "Porsche"},
  {label: "Subaru",name: "Subaru"},
  {label: "Tesla",name: "Tesla"},
  {label: "Volkswagen",name: "Volkswagen"},
  {label: "Volvo",name: "Volvo"}
  ];