export const CarMakes = [
    { id: 1, label: "Ford", name: "Ford" },
    { id: 2, label: "Honda", name: "Honda" },
    { id: 3, label: "Hyundai", name: "Hyundai" },
    { id: 4, label: "Mazda", name: "Mazda" },
    { id: 5, label: "Toyota", name: "Toyota" },
    { id: 6, label: "Mercedes", name: "Mercedes" },
    { id: 7, label: "Audi", name: "Audi" },
    { id: 8, label: "BMW", name: "BMW" },
    { id: 9, label: "Lexus", name: "Lexus" },
    { id: 10, label: "Chevrolet", name: "Chevrolet" },
    { id: 11, label: "Ferrari", name: "Ferrari" },
    { id: 12, label: "Jaguar", name: "Jaguar" },
    { id: 13, label: "Lamborghini", name: "Lamborghini" },
    { id: 14, label: "Land Rover", name: "Land Rover" },
    { id: 15, label: "Nissan", name: "Nissan" },
    { id: 16, label: "Porsche", name: "Porsche" },
    { id: 17, label: "Subaru", name: "Subaru" },
    { id: 18, label: "Tesla", name: "Tesla" },
    { id: 19, label: "Volkswagen", name: "Volkswagen" },
    { id: 20, label: "Volvo", name: "Volvo" }
  ];